#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Peter Eisenhauer
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Validate the bootstrap used for the day spread and decision stability.

Two questions, both answered against a *known* truth:

1. **Coverage** — a spread labelled "95 %" should contain the true median in
   about 95 % of repetitions. Measured per number of recorded days, this is
   what the gates in ``loop_cr_review`` are derived from.
2. **Calibration of decision stability** — a clear-cut slot should report a
   high stability, a slot sitting exactly on the threshold should not.

What this does *not* validate: the method itself. The generator draws
independent days without loop adaptation, fat/protein effects, mixed-in
corrections or drifting basal need. Real data violates all of that, so the
numbers here are an **upper bound** on how well the resampling behaves — they
say the estimator is sound, not that the carb-ratio inference is correct.

Usage:
    python3 tools/validate_bootstrap.py                 # quick run
    python3 tools/validate_bootstrap.py --reps 1000     # tighter numbers
    python3 tools/validate_bootstrap.py --markdown      # table for the docs
"""
import argparse
import sys
from datetime import datetime, timedelta
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
import loop_cr_review as core   # noqa: E402  pylint: disable=wrong-import-position

# Read before main() switches the gates off for measuring.
GATE_DAYS = core.MIN_DAYS_FOR_STABILITY
DAY_COUNTS = (3, 4, 5, 6, 8, 10, 14, 20)
TRUE_CRE = 8.0
BOLUS = 6.0


def make_rows(n_days, rng, meals_per_day=1, cre_sd=1.5, ratio=0.0, ratio_sd=0.15):
    """Synthetic slot rows whose CR_eff median is TRUE_CRE and loop share ``ratio``."""
    day0 = datetime(2026, 5, 1, 8, 0)
    rows = []
    for day in range(n_days):
        for meal in range(meals_per_day):
            rows.append({
                "time": day0 + timedelta(days=day, minutes=meal),
                "cr_eff": float(rng.normal(TRUE_CRE, cre_sd)),
                "exc": float(rng.normal(ratio * BOLUS, ratio_sd * BOLUS)),
                "bolus": BOLUS, "d4": float(rng.normal(0, 20)),
                "cho": 60.0, "cr": 10.0, "contam": False, "cgm_gap": False,
                "hypo_rescue": False, "pre": 120.0, "bg": 120.0,
            })
    return rows


def coverage_by_days(reps, n_boot, rng):
    """Share of repetitions whose spread contains the true median, per day count."""
    out = []
    for n_days in DAY_COUNTS:
        hits, widths = 0, []
        for _ in range(reps):
            stab = core.decision_stability(make_rows(n_days, rng), n_boot=n_boot)
            if stab is None or "cre" not in stab.get("spread", {}):
                continue
            low, high = stab["spread"]["cre"]
            widths.append(high - low)
            hits += low <= TRUE_CRE <= high
        gated = n_days < GATE_DAYS
        out.append((n_days, gated,
                    100.0 * hits / reps if widths else float("nan"),
                    float(np.mean(widths)) if widths else float("nan")))
    return out


def stability_calibration(reps, n_boot, rng):
    """Reported stability for a clear-cut vs a threshold-straddling slot."""
    cases = (("clear (loop share 3x threshold)", 3 * core.LOOP_RATIO),
             ("moderate (1.5x threshold)", 1.5 * core.LOOP_RATIO),
             ("borderline (exactly at threshold)", core.LOOP_RATIO))
    out = []
    for label, ratio in cases:
        pcts = []
        for _ in range(reps):
            stab = core.decision_stability(make_rows(10, rng, ratio=ratio), n_boot=n_boot)
            if stab is not None:
                pcts.append(stab["pct"])
        out.append((label, float(np.mean(pcts)),
                    100.0 * float(np.mean([p >= core.STABILITY_HIGH for p in pcts]))))
    return out


def _print_plain(cov, cal):
    print(f"Coverage of the 95 % spread (true median CR_eff = {TRUE_CRE})")
    print(" days | gated | coverage | mean width")
    for n_days, gated, pct, width in cov:
        mark = "yes" if gated else "no "
        print(f" {n_days:4d} | {mark}   | {pct:7.1f}% | {width:9.2f}")
    print("\nDecision stability by how clear the case is (10 days)")
    print(" case                                | mean | share reported 'high'")
    for label, mean, high in cal:
        print(f" {label:<35} | {mean:3.0f}% | {high:20.0f}%")


def _print_markdown(cov, cal, reps, n_boot):
    print(f"<!-- generated by tools/validate_bootstrap.py "
          f"--reps {reps} --boot {n_boot} -->")
    print(f"\n### Coverage of the 95 % spread (true median CR_eff = {TRUE_CRE})\n")
    print("| days | below gate | coverage | mean width |")
    print("|-----:|:-----------|---------:|-----------:|")
    for n_days, gated, pct, width in cov:
        print(f"| {n_days} | {'yes' if gated else 'no'} | {pct:.1f} % | {width:.2f} |")
    print("\n### Decision stability by how clear the case is (10 days)\n")
    print("| case | mean stability | reported \"high\" |")
    print("|:-----|---------------:|----------------:|")
    for label, mean, high in cal:
        print(f"| {label} | {mean:.0f} % | {high:.0f} % |")


def main():
    """Run both validations and print the results."""
    parser = argparse.ArgumentParser(description=__doc__.split("\n", maxsplit=1)[0])
    parser.add_argument("--reps", type=int, default=300, help="repetitions per cell")
    parser.add_argument("--boot", type=int, default=400, help="resamples per repetition")
    parser.add_argument("--seed", type=int, default=20260819)
    parser.add_argument("--markdown", action="store_true", help="emit a Markdown table")
    args = parser.parse_args()

    # Gates off: this measures what the gates should be, so it must see all sizes.
    core.MIN_MEALS_FOR_STABILITY = 1
    core.MIN_DAYS_FOR_STABILITY = 1

    rng = np.random.default_rng(args.seed)
    cov = coverage_by_days(args.reps, args.boot, rng)
    cal = stability_calibration(args.reps, args.boot, rng)
    core.MIN_DAYS_FOR_STABILITY = GATE_DAYS
    for n_days, _gated, pct, width in cov:
        if n_days == GATE_DAYS:
            print(f"# gate at {GATE_DAYS} days -> coverage {pct:.1f} %, "
                  f"width {width:.2f}\n", file=sys.stderr)
    if args.markdown:
        _print_markdown(cov, cal, args.reps, args.boot)
    else:
        _print_plain(cov, cal)


if __name__ == "__main__":
    main()
